JWT_SECRET_KEY = 'zhjfykgukjlkjooDYTJFHBJNKJgfhbjjknjKJKJ674bhuESRFCH65415DGHN52fxg'

REFRESH = 'refresh'
ACCESS = 'access'
USER = 'user'
TOKEN = 'token'
REFRESH_TOKEN = 'refresh_token'
DETAIL = 'detail'
SEARCH = 'search'
ID = 'id'
PK = 'pk'
PARTIAL = 'partial'
ERROR = 'error'

USER = 'user'
EMAIL = 'email'
EMAIL_OR_PHONE = 'email_or_phone'
PASSWORD = 'password'
USER_DETAILS = 'user_details'
ADDRESS_DETAILS = 'address_details'
BANK_DETAILS = 'bank_details'
EDU_DETAILS = 'edu_details'