# Generated by Django 4.2.2 on 2023-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("TRANSGENDER", "Transgender"),
                    ("PREFER NOT TO SAY", "Prefer Not To Say"),
                ],
                default="PREFER NOT TO SAY",
                max_length=255,
            ),
        ),
    ]
