# Generated by Django 4.2.2 on 2023-06-28 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
