# Generated by Django 4.2.2 on 2023-06-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_rename_userdetails_userdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.CreateModel(
            name="EduDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institute",
                    models.CharField(max_length=255, verbose_name="Institute Name"),
                ),
                (
                    "uni_board",
                    models.CharField(max_length=255, verbose_name="University / Board"),
                ),
                ("course", models.CharField(max_length=255, verbose_name="Course")),
                ("pass_year", models.DateField(verbose_name="Passing Year")),
                ("marks", models.FloatField(verbose_name="Aggregate Marks (%)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bankname",
                    models.CharField(max_length=255, verbose_name="Bank Name"),
                ),
                ("account_no", models.IntegerField(verbose_name="City")),
                (
                    "ifsc_code",
                    models.CharField(max_length=255, verbose_name="IFSC Code"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddressDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=255, verbose_name="Area")),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("state", models.CharField(max_length=255, verbose_name="State")),
                ("country", models.CharField(max_length=255, verbose_name="Country")),
                ("pincode", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
