# Generated by Django 4.2.2 on 2023-06-29 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_alter_userdetail_user_edudetail_bankdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="bankdetail",
            name="account_no",
            field=models.IntegerField(verbose_name="Account Number"),
        ),
        migrations.AlterField(
            model_name="bankdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
