# Generated by Django 4.2.2 on 2023-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_addressdetail_user_alter_bankdetail_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="ifsc_code",
            field=models.CharField(max_length=11, verbose_name="IFSC Code"),
        ),
    ]
