# Generated by Django 4.2.2 on 2023-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_bankdetail_ifsc_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="dob",
            field=models.DateField(verbose_name="dob"),
        ),
    ]
