# Generated by Django 4.2.2 on 2023-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_userdetail_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressdetail",
            name="pincode",
            field=models.IntegerField(verbose_name="Pincode"),
        ),
    ]
